#!/usr/bin/env python3

import os
import sys
import html
import os
import plotly
import socket
from helper import get_user_timeline
from nltk import TweetTokenizer
from twython import Twython
from twython import TwythonAuthError, TwythonError, TwythonRateLimitError

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets userhandler")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    s = get_user_timeline(sys.argv[1],2)
    s = str(s)
    # analyze word
    tw = TweetTokenizer()
    #print(tw.tokenize(s))
    p = tw.tokenize(s)

    score = analyzer.analyze1(p)
    if score > 0.0:
        print(colored(":)", "green"))
    elif score < 0.0:
        print(colored(":(", "red"))
    else:
        print(colored(":|", "yellow"))

if __name__ == "__main__":
    main()


#!/usr/bin/env python3

# TODO
